version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
