# Generated by Django 6.0.2 on 2026-05-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('employer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_description_text', models.TextField(blank=True, help_text='Paste the job description here.')),
                ('job_description_image', models.ImageField(blank=True, help_text='Or upload a screenshot of the job post.', null=True, upload_to='job_posts/')),
                ('generated_cv', models.TextField(blank=True, help_text='AI Generated CV matching the job description.')),
                ('generated_cover_letter', models.TextField(blank=True, help_text='AI Generated Cover Letter.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'AI Generated'), ('emailed', 'Emailed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
