# Generated by Django 6.0.2 on 2026-05-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/cover_letters/pdf/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_word',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/cover_letters/word/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/cv/pdf/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv_word',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/cv/word/'),
        ),
    ]
