# Generated by Django 6.0.2 on 2026-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0002_jobapplication_cover_letter_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_analysis_report',
            field=models.TextField(blank=True, help_text='AI Strategic Analysis: how to crack this job, key skills, and strategy.'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='apply_email_body',
            field=models.TextField(blank=True, help_text='AI Generated application email body.'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='apply_email_subject',
            field=models.CharField(blank=True, help_text='AI Generated application email subject.', max_length=255),
        ),
    ]
