# Generated by Django 6.0.2 on 2026-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0003_jobapplication_ai_analysis_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(blank=True, default='Pending AI...', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(blank=True, default='Pending AI...', max_length=200),
        ),
    ]
