JAZZMIN_SETTINGS = {
    "site_title": "Portfolio Admin",
    "site_header": "Portfolio",
    "site_brand": "Portfolio Management",
    "site_logo": "profile/Media.jpeg",
    "welcome_sign": "Welcome to the Portfolio Admin Panel",
    "copyright": "Shagor Robidas",
    "search_model": ["auth.User", "main.Profile"],
    "user_avatar": "avatar",
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.Profile": "fas fa-id-card",
        "main.Service": "fas fa-concierge-bell",
        "main.Testimonial": "fas fa-quote-left",
        "main.ContactMessage": "fas fa-envelope",
        "main.Client": "fas fa-user-tie",
        "main.SocialLink": "fas fa-share-alt",
        "resume.Education": "fas fa-graduation-cap",
        "resume.Experience": "fas fa-briefcase",
        "resume.Skill": "fas fa-tools",
        "project.Project": "fas fa-project-diagram",
        "project.Category": "fas fa-tags",
        "blog.Post": "fas fa-blog",
        "blog.Category": "fas fa-folder",
    },
    "order_with_respect_to": ["main", "resume", "project", "blog", "auth"],
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
}

JAZZMIN_UI_CONFIG = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_fixed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_revamp_treeview": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
