# Generated by Django 6.0.2 on 2026-05-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_remove_post_category_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
    ]
