# Generated by Django 6.0.2 on 2026-02-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('title', models.CharField(default='Python Backend Developer', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='you@email.com', max_length=254)),
                ('linkedin_username', models.CharField(default='@yourhandle', max_length=100)),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/yourhandle')),
                ('github_username', models.CharField(default='@yourgithub', max_length=100)),
                ('github_url', models.URLField(default='https://github.com/yourgithub')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='Your City, Country', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('about_text_extra', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_svg', models.TextField(help_text='Paste SVG path or full SVG here')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_initials', models.CharField(max_length=5)),
                ('text', models.TextField()),
            ],
        ),
    ]
