# Generated by Django 6.0.2 on 2026-02-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='clients/')),
                ('url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('title', models.CharField(default='Python Backend Developer', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='you@email.com', max_length=254)),
                ('linkedin_username', models.CharField(default='@yourhandle', max_length=100)),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/yourhandle')),
                ('github_username', models.CharField(default='@yourgithub', max_length=100)),
                ('github_url', models.URLField(default='https://github.com/yourgithub')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='Your City, Country', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('about_text_extra', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fa-solid fa-code', help_text='Font Awesome class, e.g. fa-solid fa-code', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Facebook, Twitter', max_length=50)),
                ('icon', models.CharField(help_text='Font Awesome class, e.g. fa-brands fa-facebook', max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_initials', models.CharField(max_length=5)),
                ('text', models.TextField()),
            ],
        ),
    ]
