# Generated by Django 6.0.2 on 2026-05-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_testimonial_client_initials_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
