# Generated by Django 6.0.2 on 2026-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profilesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Python Backend Developer', help_text='Comma-separated titles for typing rotation effect, e.g. Django Developer, Backend Engineer, Junior Software Engineer', max_length=300),
        ),
    ]
