# Generated by Django 6.0.2 on 2026-02-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_svg',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-code', help_text='Font Awesome class, e.g. fa-solid fa-code', max_length=100),
        ),
    ]
