# Generated by Django 6.0.2 on 2026-05-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='main.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
