# Generated by Django 6.0.2 on 2026-05-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profiletitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume PDF', null=True, upload_to='cv/'),
        ),
    ]
