# Generated by Django 6.0.2 on 2026-05-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
    ]
