# Generated by Django 6.0.2 on 2026-02-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_url',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_url',
            new_name='live_link',
        ),
    ]
